version: '3.8'

services:
  speed-backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=8080
    volumes:
      # Montar código fuente para desarrollo
      - ./src:/app/src
      # Mantener dependencias Maven en volumen
      - maven-deps:/root/.m2
    networks:
      - speed-network

  # Base de datos SQL Server (opcional para desarrollo)
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - speed-network

volumes:
  maven-deps:
  sqlserver-data:

networks:
  speed-network:
    driver: bridge 